// User Types
export const CREATE_USER_REQUEST = 'USER/CREATE_REQUEST';
export const CREATE_USER_RESPONSE = 'USER/CREATE_RESPONSE';
export const CREATE_USER_FAILURE = 'USER/CREATE_FAILURE';
export const LOGIN_USER_REQUEST = 'USER/LOGIN_REQUEST';
export const LOGIN_USER_RESPONSE = 'USER/LOGIN_RESPONSE';
export const LOGIN_USER_FAILURE = 'USER/LOGIN_FAILURE';
export const AUTH_USER_REQUEST = 'USER/AUTH_REQUEST';
export const AUTH_USER_RESPONSE = 'USER/AUTH_RESPONSE';
export const AUTH_USER_FAILURE = 'USER/AUTH_FAILURE';
export const GET_REFRESH_TOKEN_REQUEST = 'USER/GET_REFRESH_TOKEN_REQUEST';
export const GET_REFRESH_TOKEN_RESPONSE = 'USER/GET_REFRESH_TOKEN_RESPONSE';
export const GET_REFRESH_TOKEN_FAILURE = 'USER/GET_REFRESH_TOKEN_FAILURE';
export const GET_LOGOUT_RESPONSE = 'USER/GET_LOGOUT_RESPONSE';

// Common Types
export const GET_DEPARTMENTS_REQUEST = 'COMMON/GET_DEPARTMENTS_REQUEST';
export const GET_DEPARTMENTS_RESPONSE = 'COMMON/GET_DEPARTMENTS_RESPONSE';
export const GET_DEPARTMENTS_FAILURE = 'COMMON/GET_DEPARTMENTS_FAILURE';

// Commerce types
export const SET_DEVICE_REALTIME_CONNECTED = 'DEVICE/SET_REALTIME_CONNECTED';
export const SET_DEVICE_REALTIME_DISCONNECTED = 'DEVICE/SET_REALTIME_DISCONNECTED';
export const GET_COMMERCE_DATA_BY_FILTER_REQUEST = 'COMMERCE/COMMERCE_DATA_BY_FILTER_REQUEST';
export const GET_COMMERCE_DATA_BY_FILTER_RESPONSE = 'COMMERCE/COMMERCE_DATA_BY_FILTER_RESPONSE';
export const GET_COMMERCE_DATA_BY_FILTER_FAILURE = 'COMMERCE/COMMERCE_DATA_BY_FILTER_FAILURE';
export const GET_COMMERCE_DATA_BY_FILTER_RESET = 'COMMERCE/COMMERCE_DATA_BY_FILTER_RESET';
export const GET_COMMERCE_LIST_REQUEST = 'COMMERCE/COMMERCE_LIST_REQUEST';
export const GET_COMMERCE_LIST_RESPONSE = 'COMMERCE/COMMERCE_LIST_RESPONSE';
export const GET_COMMERCE_LIST_FAILURE = 'COMMERCE/COMMERCE_LIST_FAILURE';

// Complaints
export const GET_COMPLAINT_DATA_BY_COMMERCE_REQUEST = 'COMPLAINT/GET_DATA_BY_COMMERCE_REQUEST';
export const GET_COMPLAINT_DATA_BY_COMMERCE_RESPONSE = 'COMPLAINT/GET_DATA_BY_COMMERCE_RESPONSE';
export const GET_COMPLAINT_DATA_BY_COMMERCE_FAILURE = 'COMPLAINT/GET_DATA_BY_COMMERCE_FAILURE';
export const GET_COMPLAINT_DATA_BY_REGION_REQUEST = 'COMPLAINT/GET_DATA_BY_REGION_REQUEST';
export const GET_COMPLAINT_DATA_BY_REGION_RESPONSE = 'COMPLAINT/GET_DATA_BY_REGION_RESPONSE';
export const GET_COMPLAINT_DATA_BY_REGION_FAILURE = 'COMPLAINT/GET_DATA_BY_REGION_FAILURE';
export const GET_COMPLAINT_DATA_BY_DEPARTMENT_REQUEST = 'COMPLAINT/GET_DATA_BY_DEPARTMENT_REQUEST';
export const GET_COMPLAINT_DATA_BY_DEPARTMENT_RESPONSE = 'COMPLAINT/GET_DATA_BY_DEPARTMENT_RESPONSE';
export const GET_COMPLAINT_DATA_BY_DEPARTMENT_FAILURE = 'COMPLAINT/GET_DATA_BY_DEPARTMENT_FAILURE';
export const GET_COMPLAINT_DATA_BY_MUNICIPALITY_REQUEST = 'COMPLAINT/GET_DATA_BY_MUNICIPALITY_REQUEST';
export const GET_COMPLAINT_DATA_BY_MUNICIPALITY_RESPONSE = 'COMPLAINT/GET_DATA_BY_MUNICIPALITY_RESPONSE';
export const GET_COMPLAINT_DATA_BY_MUNICIPALITY_FAILURE = 'COMPLAINT/GET_DATA_BY_MUNICIPALITY_FAILURE';
export const CREATE_COMPLAINT_REQUEST = 'COMPLAINT/CREATE_REQUEST';
export const CREATE_COMPLAINT_RESPONSE = 'COMPLAINT/CREATE_RESPONSE';
export const CREATE_COMPLAINT_FAILURE = 'COMPLAINT/CREATE_FAILURE';

//Metrics types
export const SET_METRICS_BY_DEVICE_CONNECTED = 'DEVICE/METRICS_BY_DEVICE_CONNECTED';

// Module types
export const GET_SYSTEM_MODULES_REQUEST = 'SYSTEM/GET_MODULES_REQUEST';
export const GET_SYSTEM_MODULES_RESPONSE = 'SYSTEM/GET_MODULES_RESPONSE';
export const GET_SYSTEM_MODULES_FAILURE = 'SYSTEM/GET_MODULES_FAILURE';